import discord
from discord.ext import commands
from discord import app_commands
import urllib.parse
from Commands.OwnerOnly._monitor import record_command
import aiohttp
import io
import re

# Basic NSFW filter list (English and German)
NSFW_WORDS = [
    "nsfw", "porn", "sex", "nude", "naked", "dick", "pussy", "vagina", "penis", 
    "boobs", "tits", "ass", "cum", "hentai", "r34", "rule34", "rule 34", "gore",
    "blood", "murder", "kill", "rape", "child porn", "cp", "loli", "shota",
    "nackt", "porno", "schwanz", "fotze", "titten", "arsch", "sperma", "blut"
]

class ImagineCommand(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @commands.hybrid_command(
        name="imagine",
        description="Generates an AI image based on your prompt using Pollinations.ai",
        aliases=["img", "generate"]
    )
    @app_commands.describe(prompt="The description of the image you want to generate")
    async def imagine_cmd(self, ctx: commands.Context, *, prompt: str):
        record_command("imagine", str(ctx.author))
        
        # NSFW Filter check
        prompt_lower = prompt.lower()
        if any(re.search(rf'\b{word}\b', prompt_lower) for word in NSFW_WORDS):
            msg = "❌ Dein Prompt enthält unangebrachte Wörter und wurde blockiert."
            if ctx.interaction:
                return await ctx.interaction.response.send_message(msg, ephemeral=True)
            else:
                return await ctx.send(msg)

        # Defer because image generation might take a few seconds
        if ctx.interaction:
            await ctx.interaction.response.defer()
        else:
            await ctx.typing()
            
        encoded_prompt = urllib.parse.quote(prompt)
        # Using Pollinations AI without API key
        image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
        
        # Fetch the image to ensure Discord displays it properly
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(image_url) as resp:
                    if resp.status == 200:
                        img_data = await resp.read()
                        file = discord.File(fp=io.BytesIO(img_data), filename="generated.png")
                    else:
                        raise Exception("API returned non-200 status")
        except Exception as e:
            err_msg = "❌ Fehler bei der Generierung des Bildes. Bitte versuche es später nochmal."
            if ctx.interaction:
                return await ctx.interaction.followup.send(err_msg)
            else:
                return await ctx.send(err_msg)
        
        embed = discord.Embed(
            title="AI Image Generation",
            description=f"**Prompt:** `{prompt}`\n\n*Generated by Pollinations AI*",
            color=0x2B2D31
        )
        embed.set_image(url="attachment://generated.png")
        embed.set_footer(text=f"Requested by {ctx.author}", icon_url=ctx.author.display_avatar.url)
        
        if ctx.interaction:
            await ctx.interaction.followup.send(embed=embed, file=file)
        else:
            await ctx.send(embed=embed, file=file)

async def setup(bot: commands.Bot):
    await bot.add_cog(ImagineCommand(bot))
