import discord
from discord.ext import commands
from discord import app_commands
import urllib.parse
from Commands.OwnerOnly._monitor import record_command

class ImagineCommand(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @commands.hybrid_command(
        name="imagine",
        description="Generates an AI image based on your prompt using Pollinations.ai",
        aliases=["img", "generate"]
    )
    @app_commands.describe(prompt="The description of the image you want to generate")
    async def imagine_cmd(self, ctx: commands.Context, *, prompt: str):
        record_command("imagine", str(ctx.author))
        
        # Defer because image generation might take a few seconds
        if ctx.interaction:
            await ctx.interaction.response.defer()
        else:
            await ctx.typing()
            
        encoded_prompt = urllib.parse.quote(prompt)
        # Using Pollinations AI without API key
        image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
        
        embed = discord.Embed(
            title="AI Image Generation",
            description=f"**Prompt:** `{prompt}`\n\n*Generated by Pollinations AI*",
            color=0x2B2D31
        )
        embed.set_image(url=image_url)
        embed.set_footer(text=f"Requested by {ctx.author}", icon_url=ctx.author.display_avatar.url)
        
        if ctx.interaction:
            await ctx.interaction.followup.send(embed=embed)
        else:
            await ctx.send(embed=embed)

async def setup(bot: commands.Bot):
    await bot.add_cog(ImagineCommand(bot))
